### ISSUE TITLE
Determine where output from tracing will be piped

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#193]
[Slack Thread](https://celo-org.slack.com/archives/C01KT8JKQ67/p1616687832056900)

**Comment by emberian** [comment]
@yourbuddyconner currently there is a Jaeger+Zipkin collector implemented - i believe using it is a matter of using the right settings in the agent. while investing the opentelemetry ecosystem, i noticed that Grafana Agent is an OpenTelemetry Collector that implements the otlp [i keep confusing this with oltp, it's murdering me] gRPC endpoint -- should we be reporting to that endpoint, and not using the Jaeger or Zipkin collectors? it's not clear to me that Grafana Agent supports those particular APIs, although it seems [Jaeger itself is impelmenting otlp](https://www.jaegertracing.io/docs/1.21/opentelemetry/).

i feel like we already answered this on our last call and the answer is "use opentelemetry protobufs", do you think otherwise? i believe [grafana uses the OpenTelemetry Collector](https://grafana.com/blog/2021/04/13/how-to-send-traces-to-grafana-clouds-tempo-service-with-opentelemetry-collector/) to implement API translation -- if we used Jaeger, would we need to additionally deploy the Collector and not just the Agent?
