### ISSUE TITLE
`optics-xapps` does not properly verify `UpgradeBeacon` contracts

### ISSUE THREAD

**Issue by prestwich** [celo-org/optics-monorepo#589]
this occurs because the deploy process uses the  `UpgradeBeacon` typechain generated by optics-core

edit:
hmm, my hypothesis may be wrong. it is failing to verify in `core` as well now 🤔

**Comment by anna-carroll** [comment]
hmmm can you elaborate? checking a beacon from the latest deploy, it seems to be verified: https://kovan.etherscan.io/address/0xc63e0e2Db5A568Fa86416eF1573815f7d644FDE3#code

**Comment by prestwich** [comment]
> hmmm can you elaborate? checking a beacon from the latest deploy, it seems to be verified: https://kovan.etherscan.io/address/0xc63e0e2Db5A568Fa86416eF1573815f7d644FDE3#code

it errors on verification submission because it can't find matching local bytecode, which I think means the local byte code changed during the hardhat clean step

The latest contracts are still verified because they are identical to previously verified contracts

**Comment by anna-carroll** [comment]
super interesting. so, we just did a new deploy where the source code for the `UpgradeBeacon` was [changed ever-so-slightly](https://github.com/celo-org/optics-monorepo/pull/628/commits/87f888c75afb91ec07bbb953e1141e51eb736bfd). looking at the latest deploy, the very [first upgrade beacon deployed](https://kovan.etherscan.io/address/0x4F9a3F26C4314d652dEd38745c3A5dadbDfAEf6A#code) was verified properly, and all [subsequent upgrade beacons](https://kovan.etherscan.io/address/0x015B0B6bD110EC75d8c05aCE20E6ff7ae595aEC2#code) failed to verify directly, but are verified because they match the source code of the first one. 

so it looks like it's just rejecting subsequent verifications once it's already seen & verified the same bytecode - but it's only doing it for this particular contract. other contracts like the UpgradeBeacon Proxy are not affected by the same issue. 

i don't think this is high priority to address, though, because it seems like we are able to verify changes in code and should be able to verify on mainnet too
